import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// componenets
import Footer     from  "./components/Footer/Footer";
import Menu       from  "./components/Menu/Menu";
import NavBar     from  "./components/NavBar/NavBar";
import BreadCrumb from  "./components/BreadCrumb/BreadCrumb";
// end components

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <div className="flex-row">
          <Menu/>
          <NavBar/>
          <BreadCrumb/>
        </div>
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <Footer/>
    </html>
  );
}
